### ISSUE TITLE
Kernel 4.19 support

### ISSUE THREAD

**Issue by maartenvanmalland** [schoebel/mars#21] opened 2019-02-13 14:51 UTC
Hello,

I think this is an amazing project with big potential. However, it looks like that the newest supported kernel is 4.4, which was released more than 2 years ago. That's a shame really...

Is there any chance we'll see support for newer kernels? You mentioned before that the Linux block layer changes continuously, but I think that has stabilized quite a bit now.

Many thanks!

**Comment by schoebel** [comment] 2019-02-13 16:31
Hi Maarten,

I am currently working on compatibility to kernel 4.9. It is already ready for release, but tests are currently running / not yet fully completed. A pre-release for 4.9 was pushed under WIP-for-Moritz some days ago, but I discovered some issues which led to a delay (und thus I retracted that branch today).

I want to keep the stable branch really as "stable" as possibile, and to minimize any risks (in favour of time).

I will push the newest version once I am sure that it has no known issues anymore. Let's see if I can push an itermediate WIP branch for you,

After that, more work for even more recent kernels is already on my roadmap.

Compatibility to a rage of kernels is really like hell. It is not only porting, but also regression testing. 

Therefore going kernel upstream becomes more and more important, and I would much appreciate more help from the kernel hacker community.

Cheers,

Thomas

**Comment by schoebel** [comment] 2019-02-14 16:49
Hi Maarten,

I just pushed branch WIP-for-Maarten-and-Moritz. Please don't use for critical data yet. But my first tests are encouraging now.

As you can see, there are some intermediate steps to be released, in oder to have some "savepoints" inbetween ;)

Please help me by giving feedback,

Thomas

**Comment by maartenvanmalland** [comment] 2019-02-14 20:42
Hi Thomas,

Thank you very much for pushing this branch. On my main server I'm running kernel 4.19 so I can't really test this version there. However, it's fairly easy to fire up some VM's for me and setup a test environment for 4.9. This however will take a bit more time, so I'm afraid it will take a couple of days to give feedback. 

Thanks again,

Maarten

**Comment by subbergunz** [comment] 2019-03-21 13:25
Thank you Thomas. I compiled, installed and run on Debian 9.8 stretch. There is not a very big load on this pair of servers, I am replicating just one device, but apparently everything is working.

This is what I did to compile, some adaptation is probably always required:

`
cd /usr/local/src
apt-get update
apt-get build-dep linux
apt-get install fakeroot
apt-get source linux
cd linux-4.9.144/
cp /boot/config-4.9.82 .config
make olddefconfig
make kernelversion
cd ..
wget --no-check-certificate https://github.com/schoebel/mars/archive/mars0.1astable71.zip
unzip mars0.1astable71.zip
mv mars-mars0.1astable71 linux-4.9.144/block/mars
cd linux-4.9.144

# The following shows a few offsets, and no failures
patch -p1 < block/mars/pre-patches/vanilla-4.9/0001-mars-minimum-pre-patch-for-mars.patch
# The following goes through silently
patch -p1 < block/mars/pre-patches/vanilla-4.9/0002-mars-SPECIAL-for-in-tree-build.patch # Dritta
make clean
# In the following dialog, choose to compile mars as module, and hit return for everything else
make oldconfig
# This require hours, the number appended at the end of version should be higher than uname -a
make deb-pkg LOCALVERSION=-mars KDEB_PKGVERSION=$(make kernelversion)-2
cd ..
dpkg --install linux-image-4.9.144-mars_4.9.144-2_amd64.deb
dpkg --install linux-headers-4.9.144-mars_4.9.144-2_amd64.deb
dpkg --install linux-libc-dev_4.9.144-2_amd64.deb
reboot
`
I installed the userspace part in a very naive way:
`
cp /usr/local/src/linux-4.9.144/block/mars/userspace/marsadm /usr/local/bin
mkdir -p /usr/local/share/man/man8
cp /usr/local/src/linux-4.9.144/block/mars/userspace/marsadm.8 /usr/local/share/man/man8
cp /usr/local/src/linux-4.9.144/block/mars/userspace/systemd/mars.service /etc/systemd/system/
echo 'RequiredBy=libvirt-guests.service' >> /etc/systemd/system/mars.service
# The output of the following is pasted into crontab -e:
cat /usr/local/src/linux-4.9.144/block/mars/userspace/cron.d/mars
`

I will gradually add devices, and keep you informed of any news. Thank you again.

             Bergonz

**Comment by schoebel** [comment] 2020-04-04 08:56
I leave this open, to remind me.

Currently, only kernels up to 4.14 are supported.

Reason: look at the table at https://www.kernel.org/category/releases.html and determine the longest LTS _end_ _date_ in column "Projected EOL".

I always treat this longest LTS kernel as _required_ to be supported (as best as possible).

Please consider helping me by doing ports.

In the meantime, there is a support infrastructure for kernel-porting in compat.h. Thus it should be easier now. It could become a challenging task for kernel juniors.

**Comment by schoebel** [comment] 2021-02-13 11:29
Hi all,

I pushed WIP-kernel-5.4. It passes my lab tests, but I wouldn't call it "stable" yet.

Possibly in a few months, it could be rolled out to 1&1 ShaHoLin, collecting thousands and then millions of operation hours there. Only thereafter I would call it "HA proven".

Notice that there is a new generation of pre-patches for the newer kernels. Kernel upstream has introduced the new ksys_* internal calling convention, superseding the old assembler-based sys_* convention. This will help me in future, but I had to extend the new interface with a few AIO calls.

I have not yet runtime-tested any build without the new pre-patches, but just compile-tested them.

Anyway, I cannot recommend builds without the pre-patch, not only because of much worse performance (sio in place of aio), but also because of an upstream kernel endless loop which can seriously harm the user experience. The fix for this bug is included, and IMO is a must. Otherwise any network outage may trigger a kernel soft lockup.

I would be happy receiving your feedback, and hope you are all fine and stay healthy.

Cheers,

Thomas

**Comment by rusticek** [comment] 2021-04-21 13:01
Hi,

is function of detecting prepatch correctly working with newer kernels >4.16? Im having trouble with 4.19 and 5.4 that modinfo saying no_prepatch. Im applying all 3 patches for the specific kernel, enabling mars module and successfully compiling. With 4.14, that im compiling the same way, is modinfo saying has_prepatch.

Thanks

**Comment by schoebel** [comment] 2021-04-22 16:19
Hi Rusticek, I just posted a reply (with a fix for your problem) in a separate thread. I will close this thread now, please answer in the new thread.

**Closed by schoebel** 2021-04-22 16:19 UTC
Labels: help requested
