### ISSUE TITLE
‘const struct file_operations’ has no member named ‘aio_fsync’

### ISSUE THREAD

**Issue by subbergunz** [schoebel/mars#17] opened 2018-03-02 14:11 UTC
I am trying to compile the current debian 9 kernel, i.e. 4.9.82, with mars0.1stable53 prepatches, from block/mars/pre-patches/vanilla-4.7/ and I get:

<pre>
block/mars/kernel/mars_aio.c: In function ‘aio_event_thread’:
block/mars/kernel/mars_aio.c:676:35: error: ‘const struct file_operations’ has no member named ‘aio_fsync’; did you mean ‘fsync’?
         !output->mf->mf_filp->f_op->aio_fsync) {
                                   ^~
</pre>

Does this look like a quick fix, or a more serious issue?

Regards,
                           Bergonz

**Comment by subbergunz** [comment] 2018-03-02 15:19
I should have researched more. According to:

http://lkml.iu.edu/hypermail/linux/kernel/1610.3/05529.html

> drops the never implemented aio_fsync methods ...
> No user visible change as we always
> ended up returning EINVAL anyway.

so I understand that this code: 
<pre>
                             // workaround for non-implemented AIO FSYNC operation
                                if (output->mf &&
                                    output->mf->mf_filp &&
                                    output->mf->mf_filp->f_op &&
                                    !output->mf->mf_filp->f_op->aio_fsync) {
                                        mars_trace(mref, "aio_fsync");
                                        _enqueue(other, mref_a, mref->ref_prio, true);
                                        continue;
                                }
                                err = aio_submit(output, mref_a, true);
                                if (likely(err >= 0))
                                        continue;
</pre>
should become simply:
<pre>
                                _enqueue(other, mref_a, mref->ref_prio, true);
                                continue;
</pre>
Am I understanding iit right?

**Comment by schoebel** [comment] 2018-03-05 19:42
Hi Bergonz,

yes the aio_fsync operation can be generally skipped because it has never been used. But this is not the real problem.

The real problem is a bit more complex: starting with kernel 4.7, there are some more changes at the block layer of the kernel. Some of them change the kernel context of calls from the kernel to MARS: sometimes also running under workqueue context, thus schedule() (or other kinds of sleeping) cannot be called any more.

The problem is solvable, but needs some time (also for testing).

Caution: the workqueue context problem is often not noticed under typical workloads, but can lead to scarce deadlocks etc, e.g. when xfs umount() flushes its buffers in workqueue context even after umount() had successfully returned to userspace.

After debugging with the deadlock validator and other kernel debugging options, this kind of behaviour needs some thorough stress testing under high load.

I even have worked on this topic one year ago for a few weeks, but I had no further time because other things were more imporant at 1&1 (only kernel 4.4 is needed at the moment).

Pushing these WIP patches makes no sense because they don't work at the moment. I don't want to push crap. And the patches need some rebasing too.

Please stay patient. I have the 4.7 compatibilty on my pushback list ;)

Hope you enjoy MARS with a lower stable kernel.

As soon as I have something which is no longer pure crap, I will push it for you. Then you can help with testing.

Cheers,

Thomas

**Comment by borkd** [comment] 2018-03-20 23:59
I'd also like to test. Like subbergunz, I'm using Debian stretch and current kernel 4.9.82.

**Comment by schoebel** [comment] 2020-04-04 08:47
Has been fixed in the meantime. Currently, kernels up to 4.14 are supported.

**Closed by schoebel** 2020-04-04 08:47 UTC
